# Generated by Django 3.1.6 on 2021-05-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('mtitle', models.CharField(max_length=225)),
                ('mtype', models.CharField(max_length=225)),
                ('mprice', models.CharField(max_length=225)),
                ('mimg', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('mdesc', models.TextField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
