# Generated by Django 3.1.6 on 2021-05-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0003_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='mimg',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='mprice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='mtitle',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='menu',
            name='mtype',
            field=models.CharField(max_length=50),
        ),
    ]
