# Generated by Django 3.1.6 on 2021-05-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0005_auto_20210521_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='mimg',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
