# Generated by Django 3.1.6 on 2021-05-21 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0006_auto_20210521_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='mimg',
        ),
    ]
