# Generated by Django 3.1.6 on 2021-05-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0007_remove_menu_mimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('cname', models.CharField(max_length=90)),
                ('cemail', models.CharField(max_length=90)),
                ('address', models.CharField(max_length=90)),
                ('orderdate', models.DateTimeField(max_length=30)),
            ],
        ),
    ]
