# Generated by Django 3.1.6 on 2021-05-29 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0008_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='orderdate',
        ),
        migrations.AddField(
            model_name='orders',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
