# Generated by Django 3.1.6 on 2021-06-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0011_orders_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cardnumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cvv',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='year',
            field=models.IntegerField(),
        ),
    ]
